services:

  shopsphere-gateway:
    container_name: shopsphere-gateway

    build:
      context: ../services
      dockerfile: ShopSphere.ApiGateway/Dockerfile

    ports:
      - "7000:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__identityCluster__Destinations__destination1__Address=http://shopsphere-api:8080/
      - ReverseProxy__Clusters__productCluster__Destinations__destination1__Address=http://shopsphere-product-api:8080/
      - ReverseProxy__Clusters__orderCluster__Destinations__destination1__Address=http://shopsphere-order-api:8080/
      - ReverseProxy__Clusters__inventoryCluster__Destinations__destination1__Address=http://shopsphere-inventory-api:8080/
      - ReverseProxy__Clusters__paymentCluster__Destinations__destination1__Address=http://shopsphere-payment-api:8080/
    depends_on:
      - shopsphere-api
      - shopsphere-product-api
      - shopsphere-order-api
      - shopsphere-inventory-api
      - shopsphere-payment-api

  shopsphere-payment-api:
    container_name: shopsphere-payment-api

    build:
      context: ../services/PaymentService
      dockerfile: ShopSphere.PaymentService.API/Dockerfile

    ports:
      - "5004:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ShopSpherePaymentDb;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True

  shopsphere-inventory-api:
    container_name: shopsphere-inventory-api

    build:
      context: ../services/InventoryService
      dockerfile: ShopSphere.InventoryService.API/Dockerfile

    ports:
      - "5003:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ShopSphereInventoryDb;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True

  shopsphere-order-api:
    container_name: shopsphere-order-api

    build:
      context: ../services/OrderService
      dockerfile: ShopSphere.OrderService.API/Dockerfile

    ports:
      - "5002:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ShopSphereOrderDb;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True
      - Services__ProductService=http://shopsphere-product-api:8080/
      - Services__InventoryService=http://shopsphere-inventory-api:8080/
      - Services__PaymentService=http://shopsphere-payment-api:8080/

    depends_on:
      - shopsphere-product-api

  shopsphere-product-api:
    container_name: shopsphere-product-api

    build:
        context: ../services/ProductService
        dockerfile: ShopSphere.ProductService.API/Dockerfile

    ports:
        - "5001:8080"

    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ShopSphereProductDb;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True
        - Redis__ConnectionString=shopsphere-redis:6379

    depends_on:
        - shopsphere-redis

  shopsphere-api:
    container_name: shopsphere-api

    build:
      context: ../services/IdentityService
      dockerfile: ShopSphere.IdentityService.API/Dockerfile

    ports:
      - "5000:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ShopSphereIdentityDb;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True
      - Redis__ConnectionString=shopsphere-redis:6379

    depends_on:
      - shopsphere-redis

  shopsphere-redis:
    image: redis:7-alpine

    container_name: shopsphere-redis

    ports:
      - "6379:6379"